iFixit/pulldasher

bin/pulldasher
bower.json

The project is licensed under the MIT License, so the bower.json configuration
file should reflect that.
This also changes the hashbang in bin/pulldasher to /usr/bin/env instead of /bin/env .
On both Ubuntu and OSX I was recieving a 'bad interpreter' error, because env 
was under /usr/bin/ instead of /bin/.
cr_req 0

Update bower.json license and change the hashbang of bin/pulldasher

---

controllers/main.js
views/standard/index.html
views/standard/spec/debugIndicators.js

This adds functionality to only show the debug indicators when the `debug` setting in 
`config.js` is set to `true`.
This feature also allows the user to enter debug mode on the client without having 
to reload the page and lose the current state they have on the page.
To enter debug mode manually, they can open the console and run `App.debugStart()`.
This will set the `App.debug` value to `true` and then rerender the view with the debug indicators.

Don't always show debug indicators

---

views/standard/less/pull.less
views/standard/spec/columns.js
views/standard/spec/indicators.js

This alters the sorting preferences for columns so that pulls with milestones
are placed near the top, and milestones that are past their due date are
sorted even higher towards the top.
Fixes #5

Milestones: Sort columns based on milestone due date

---

app.js
lib/git-manager.js

Calling `bin/pulldasher rebuild-history` will rebuild the entire
`metrics` DB looping over all pulls, both open and closed.
qa_req 0 (I tested it)
Closes #18

Metrics: rebuild all pull history with cli arg

---

README.md
config.example.js
public/js/IndicatorFilter.js
public/js/PullFilter.js
public/js/pageIndicatorHandler.js
views/README.md
views/standard/spec/columns.js
views/standard/spec/debugIndicators.js
views/standard/spec/index.js
views/standard/spec/indicators.js
views/standard/spec/pageIndicators.js
views/standard/spec/utils.js

Add lots of documentation (mostly about use and frontend customization).
--
This adds a documentation comments in many of the pulldasher
configuration and source files, especially `config.js`. The comments
should make it a lot easier to set up pulldasher with the correct tokens
and secrets from Github.
This also expands the README.md to include more information about
configuration, setup, and Pulldasher itself.
cr_req 1
qa_req 0

Add  documentation

---

0001-comments--add-comment_type.sql
controllers/githubHooks.js
lib/git-manager.js
models/comment.js
models/db_comment.js
schema.sql

Now, all comments (pull and pull-review) are stored in the DB
and on the Pull objects in the Pull.comments array.
This will be useful for analysis on the DB side and could be useful on
the client side to remind you which pulls you've been active on.
Note: I've added our first migration. Dealing with them should be
pretty simple, just run (manually) the ones that haven't been run.
Closes #28

Pull Request Diff Comments: pay attention!

---

app.js
lib/git-manager.js
lib/rate-limit.js

All hail the rate limit!
This adds some smarts to our github usage and will allow requests to
go through unimpeded until we get to the choke point, at which point
we start throttling requests such that we stay *just* under the rate
limit.
Obviously, not knowing the future means we can't be all that smart
about it.
The delay is such that if you have an unlimited number of requests
coming in, we'll stay just below the rate limit. If you reach the
choke point but only have a few more requests, they will be throttled
unnecessarily, but we'll just have to live with that.
This means that now, the rebuild-history option will totally work
without hitting the rate limit. Also, change rebuild-history to
operate on pulls one at a time, instead of thousands in parallel.
Closes #33

Github: obey the rate limit!

---

config.example.js

Github started making their emoji auto-completor inject unicode emojis
instead of ascii representations like :+1: or :smile:. This updates
the regex to detect unicode ranges that contain emojis. The regex is a
bit more permissive than needed, but the set symbols that are used
as emojis is dispersed across a smattering of unicode ranges.
Closes #26

Example config: update to handle unicode emojis as well

---

app.js
config.example.js
controllers/githubHooks.js
lib/db-manager.js
lib/git-manager.js
lib/refresh.js
migrations/0004-issues--rename-some-columns.sql
migrations/0005-issues--rename-milestone_due_date.sql
models/db_issue.js
models/issue.js
models/label.js
models/pull.js
schema.sql

There are a few other semi-related things in here too:
* Record labels on issue events like *labeled* and *unlabeled*
* Record labels upon refreshing an issue
* Move some git-manager.js functions out of exports
* Change the column names in the issues table to be consistent with the
pulls table
Closes #42

Issues: record issue labels as well

---

lib/git-manager.js
lib/utils.js
migrations/0006-date-columns--null-out-zeros.sql
models/issue.js
models/label.js
models/pull.js
models/signature.js

Previously every missing or null date field (from the github api)
would end up as 0 in the database instead of NULL because
we were always doing `new Date(thing.date)`.
I've extracted the most likely behavior into a utils function
and used it wherever it made sense. This was nearly everyplace besides
the client and places where we were explicitly comparing Date objects.
Closes #47

Dates: deal with null values

---

Gruntfile.js

An issue was filed on jshint's github about this
https://github.com/jshint/jshint/issues/2922. The solution seems to be to
explicitly define a reporterOutput option with a value of empty string.
After making this change, grunt builds ran flawlessly.

Fix null error in jshint grunt plugin

---

app.js

The only fonts we use are the font-awesome ones where are not present
in the bootstrap fonts dir. It seems we dont' use the bootstrap glyph
fonts at all so it's Ok to change this dir.
Before, we were getting a 404 when looking for font-awesome files in
the /fonts dir. After, they exist!
Closes #55

/fonts path: serve the correct directory

---

controllers/githubHooks.js

We've seen this in practice and the docs mention it; we can receive
issue events about pull requests. Thankfully they also mention how to
distiguish them. Previously, we didn't and would occasionally get
issues records created for pull requests (instead of records in the
pulls table).
CC @entendu
Note: there are a few other small refactorings in here too, go
commit by commit for CR.
Closes #57

Hooks: deal with issue events about pull requests

---

controllers/githubHooks.js
lib/get-user-id.js
lib/get-user-login.js
lib/git-manager.js
models/comment.js
models/db_comment.js
models/db_pull.js
models/db_signature.js
models/issue.js
models/pull.js
models/signature.js

Sometimes github user accounts are deleted.
When they are included in an api response, the user looks like:
Normal User:
issue: {
user : {
login: "danielbeardsley",
url: ...
}
}
Deleted User:
issue: {
user : null
}
This change wraps all places where we access properties of the user
object in an api response.
Most places would have previously crashed the app. The one that
changed now produces "ghost" instead of NULL (just like github's
web UI). This allows the DB columns to still be NOT NULL. Keeping them
from being null makes it so we don't have to deal with nulls in the
rest of our code.
Perhaps in the future we'll want to do something different, but
this is safe for now.
Note: I found these by:
git grep -E "\.(sender|actor|user|assignee)"
And looking at the backend files that matched. …

Github API Responses: don't depend on user.login

---

lib/authentication.js

We were passing both a success and error callback to `passport.authenticate`,
which doesn't match the way that that function handles errors.
`passport.authentiate` passes an error object as the first parameter to the
first callback which we now check before operating on the response from the
OAuth authentication.
Based on the passport source, the second callback was being clobbered when the
second argument was also a callback.

Handle passport authentication errors correctly

---

Gruntfile.js
lib/authentication.js

Previously if you accessed pulldasher using a query param like `assigned` or
`milestone` and you were placed in an OAuth redirect, your query params would
be forgetten after returning from OAuth redirects.
This stores the original URL in the session so that when the user gets back
from an OAuth redirect, the app redirects them to their original URL and not
just `'/'`.
CC @sctice

Redirect to original URL after OAuth success

---

app.js
controllers/githubHooks.js

This adds more explicit values to `express-session` and removes the use of the
deprecated `req.param` method.
`req.param` is deprecated because it searches for a value from the
* route matching
* query params
* request body
There are individual functions to use for each of those, so it's recommended to
use those instead of the larger generic one. This was used for something that's
always a query param, so the usage is switched to `req.query`.

Fix deprecated express middleware uses

---

app.js
bin/pulldasher
bin/refresh-all-issues
bin/refresh-all-pulls
bin/refresh-issue
bin/refresh-open-issues
bin/refresh-open-pulls
bin/refresh-pull
controllers/githubHooks.js
lib/authentication.js
lib/db-manager.js
lib/debug.js
lib/git-manager.js
lib/pull-manager.js
lib/rate-limit.js
lib/refresh.js
models/db_comment.js
models/issue.js
models/pull.js

When you're logging the output through any modern logging
system (syslog, journalctl, ...) a timestamp is prepended anyway.
There's no point in adding a second timestamp.
Let's make that configurable using an ENV variable.
Closes #38

Debug Log: allow disabling of timestamp

---

views/standard/less/components/pull.less
views/standard/less/themes/colors/day_colors.less
views/standard/less/themes/colors/night_colors.less
views/standard/spec/columns.js

In https://github.com/iFixit/pulldasher/issues/87 we decided to add an `external_block` label to pulls that require input or QA from someone outside of our department. When you add the `external_block` label to a github issue a red eye with a slash with show up next to the pull in the QAing column.
Come talk to me and we can QA this together. Or I can help get you set up with docker and explain how to QA it on your own. 
Closes #99

Add external block icon

---

lib/db-manager.js

This query was really slow cause the join was on a column
that wasn't indexed. After examining the usage of this func,
we only need the columns from pull_signatures anyway.
It went from 1400ms to < 10ms.
Closes #104

db-manager: simplify signatures query

---

controllers/githubHooks.js

There are separate events for pulls, and I can't think of any case where
an issue event needs to have a pull updated.
QA:
Replay the previous webhooks that failed, or get github to fire those webhooks by manually doing those operations. Issues events should no longer make pulldasher restart.

Stop trying to update pull on issue events

---

views/standard/spec/pageIndicators.js

We were using a leftover `org` variable to construct a string to the
github page where all pulls with the cryo label exist. The new way a
repo is represented is a string like "org/repo", so instead of relying
on an org and a repo, we can just include that string as the first two
parts of the github URL path.

Use new org/repo string for Cryogenic pull links

---

controllers/githubHooks.js
lib/git-manager.js
models/label.js

The `Label` constructor and its callsites were using different numbers of
parameters. For the few that were using too little, the fields were
being incorrectly set to the wrong label fields, i.e. the repo field
would be set to the user value.
This removes the extra constructor parameter and removes arguments left
over from before the `repo_name` column was removed.
qa_req 0
This also works for label add and delete webhooks.
Closes #117

Labels: Remove extra repo name parameter

---

app.js

This was causing the pulldasher app to go over its rate limits pretty
frequently. It was extremely problematic since it would crash on hitting
the rate limit, and immediately crash into the rate limit again.
When there are a very large number of repositories and thus many items
pulldasher needs to lookup, it approaches the rate limit very quickly.

Don't automatically refresh open pulls on start

---

docker-compose.yml
entrypoint.sh

When the DEBUG environment variable is set, make sure to start
Pulldasher with the `--inspect` flag. This lets you connect a debugger
remotely (DevTools for Node, node-inspector).
cr_req 1
qa_req 0 I started up a debug instance of pulldasher with Chrome DevTools open and successfully attached.

Start node inspector when DEBUG is set

---

views/standard/spec/columns.js

If a pull is externally blocked, there's no need to look at it. Let's move it to the bottom of the column and out of sight.
QA Instructions:
These changes are live on our pulldasher. As long as external_block pulls are consistently at the bottom of the queue for a few days or so we can sign off on this.
Closes #119

Add rule for external_block sorting

---

views/standard/spec/indicators.js

This is by @evannoronha.
We previously only showed tooltip text for milestones with due dates. Now every pull with an attached milestone will have a tooltip that displays the name of the milestone.
QA
Check this branch out in /opt/pulldasher and mouseover some milestone indicators. Make sure they all have tooltip text on hover.

Show tooltip text for milestones with no due date.

---

public/js/Pull.js
views/standard/spec/columns.js

This pull changes QA column behavior to include any pulls that don't have CI set up in their repo. Previous behavior would block these pulls from showing up outside of CI-Blocked and CR columns.
| Current | Updated |
|---------|---------|
| ![image](https://user-images.githubusercontent.com/1361631/36055315-85799ff0-0db0-11e8-974c-874147d23576.png) | ![image](https://user-images.githubusercontent.com/1361631/36055310-7c611a74-0db0-11e8-8765-6c7aaacbf4f2.png) |
CR
--
- `pull.status.commit_status` is an object that is falsey (`null`) if there's no CI set up, and truthy if there is CI but it's failing or not ran yet.
QA
--
Talk to me about how to set up a test instance of Pulldasher.
Closes #130

Shows pulls from repos without CI in QA column

---

bin/refresh-open-pulls
lib/authentication.js
lib/db-manager.js
lib/git-manager.js
lib/rate-limit.js
lib/refresh.js
package-lock.json
package.json

A long time ago we forked `node-github` in order to add some changes to it. We made a pull request on the upstream and then forgot to track the upstream once our forked changes made it back in.
Our fork is about 10+ major versions behind and at least one package rename, so this adds the necessary changes to track the current version of `@octokit/rest`.
In order to cause the least number of changes to Pulldasher, this only updates the underlying SDK calls underneath our own API in `git-manager.js`. Once this is stable for a little while we can look into removing our secondary API in favor of just using `@octokit/rest` directly.
Closes #75

Upgrade node-github to @octokit/rest

---

package-lock.json
package.json

These changes were primarily done by `npm audit fix`.

Updates less to ^3.8.1 to pull in npm audit fixes

---

Dockerfile
controllers/main.js
lib/git-manager.js
lib/utils.js
views/layout.html
views/standard/spec/debugIndicators.js

There's actually a bunch of fixes here all detailed in the commit
messages:
* Use bluebird promises in one last place
* Use correct octokit api for fetching issues
* Re-add the accidentally rate limit
* Add logging by default to the Dockerfile
* Template rendering: turn off useless debug mode

Issue Refreshing: fix it

---

app.js
package.json
public/js/socket.js

When you focus away from the tab for a while and then come back,
the page refreshes... Wat?
Turns out chrome kills the connection (or something). After coming back,
socket.io fires a 'connect' event. We then fire the 'auth' event
to the backend thinking this is the first time we connected.
The server can't make sense of our nonce and so returns a "fail,
please refresh" response.
Now, let's just only ever listen for one auth event per server-side
connection. So long as the server thinks they're still connected,
we don't care if the client thinks it's connecting for the first time
or reconnecting after being away.
Also, add a manual 'build' npm command. Previously, it only happened on
post-commit.

Socket.io reconnection: stop refreshing the page

---

.eslintrc.json
lib/authentication.js

Hey everyone 👋, I was playing around with Pulldasher and ran into an issue with GitHub authentication where it would still check my org membership even if I left the requireOrg config variable as false.
This makes a change to not check a user's org membership if the
requireOrg field in config.js is falsy. Currently Pulldasher always
makes a call to GitHub to check the user's membership, when it shouldn't
if the user doesn't want to require an org.
I tested this with a requireOrg value of `iFixit`, in which I was not allowed to view my local pulldasher website, and with a value of `false`, in which I could view my local instance of pulldasher.

Authentication: Don't check org membership if not required

---

lib/authentication.js

This includes some CR changes that didn't make it into the previous PR haha.
This also adds a catch handler for the org membership check promise and
passes the error to `next` to be handled. Currently this goes to the
default error handler, but before this the unhandled promise rejection
would trigger a console warning but the response wouldn't end because the
middleware chain wouldn't continue.
Now the error message is printed out and the response is ended
successfully.
A few thoughtful CRs is enough. Worst case is login breaks and we revert.
qa_req 0

fix(authentication): deduplicate req.logIn function

---

lib/db-manager.js
lib/git-manager.js
migrations/0011-add-build-status-context.sql
migrations/schema.sql
models/db_status.js
models/pull.js
models/status.js
public/js/Pull.js
views/standard/less/components/pull.less
views/standard/spec/indicators.js
views/standard/spec/pageIndicators.js

Support multiple statuses per commit:
* Injest them from the webhooks
* Save them to the DB
* Load them from the DB
* Request them from the API
* Maintain them in the memory model
* Update the UI
* Split the existing green/red CI status bar into vertical pills
with one per status
Closes #72

Multiple Commit Statuses: Implement MVP

---

public/js/Pull.js

Was accessing the wrong property name for the state of the commit
status!

Pull model on client: fix build_succeeded() function

---

app.js

In order to mount the pulldasher configuration as a secret, we need to be able to mount a volume, not a single file. The `config.js` file was hardcoded here to `/opt/pulldasher/config.js`. Let's allow optionally specifying the path on the environment.
cr_req 1
qa_req 0
CC @danielbeardsley

Allow overriding the config path from the ENV

---

migrations/0012-add-pull-diff-info.sql
migrations/schema.sql
models/db_pull.js
models/pull.js

This will give us the ability to track `additions`, `deletions`, and
`changed_files` on pulls.
QA
----
I ran a local instance of pulldasher and confirmed that these fields
were being filled in in the `pulls` table for new pulls. Anything else
we should check?

Pull Diff: store data in DB

---

app.js
lib/config-loader.js
lib/pull-manager.js
lib/utils.js

In a previous pull, config.repos learned to handle an array of objects
instead of just an array of strings. Not all usages of the config.repos
setting were updated to handle the different ways of representing the
data.
Instead of handling both formats in each usage, let's normalize when
loading the config.
Connect #167

config.repos: normalize repo list on load

---

app.js
lib/config-loader.js
lib/pull-manager.js
lib/refresh.js
lib/utils.js

Previously we hadn't done this because a boot-loop could cause you
to burn through your API rate limit pretty quickly. But in practice
that doesn't happen anymore, and this is worth it.

Pulls: refresh open pulls on app start

---

config.example.js

QA
---
Copy this new regex to from the example config to the real config, and
make sure it:
- works with emojis that our current regex doesn't like 🪂
- doesn't match things that aren't emojis
cr_req 1
CC @ianrohde
On Deploy
---
Copy this new regex to from the example config to the real config.
Closes iFixit/pulldasher#176

Support more emojis in signoffs

---

package-lock.json
package.json

Background
===
@davidrans tried deploying his recent change #177 but we forgot about an unresolved rollback that happened a month or two ago.
Let's look into why the jQuery bump caused issues, but let's run the
other recent changes in the mean time.
This should allow us to use the most recent changes aside from those in https://github.com/iFixit/pulldasher/pull/173
QA
===
Run this branch and see if you can spot any immediately obvious problems. If there's nothing to glaring, let's merge this and let it run in the wild.

Temporarily revert jQuery bump

---

public/js/Pull.js

Let's restrict the number of signatures each person can make to one. This will be slightly more bother when carrying over a CR, but it will reduce the risk of accidentally deploying a pull which only one person has signed off on.
We encountered an incident where a person signed off twice, once before a commit was pushed and once after, but because the commit date was before the first signoff date, both signoffs were considered valid. The problem with a signoff not being invalidated by a commit which is pushed after the signoff is still not solved, but this change at least reduces the risk of such an incident resulting in insufficiently-reviewed code being deployed.

Allow one signature per person

---

lib/rate-limit.js

After bumping the ocktokit version we didn't realize the method of
extracting the headers (for ratelimit) had changed.
CC @addison-grant
Closes iFixit/pulldasher#184

github rate limit: use new method of getting headers

---

config.example.js

The docs on this weren't clear on all the requirements to get the webhook working.

Pulldasher: Clarify webhook `secret` param

---

README.md
views/README.md
views/standard/less/components/header.less
views/standard/spec/pageIndicators.js

The frozen indicator has been targeted for termination.  Let's get that done.
Besides falling into disuse for the most part, it doesn't work correctly with multiple repos either.  The link is built from the repo  of the first frozen pull it comes across.  On the `comior` instance it appears to point to a dead repo?
Closes #136

Remove the frozen indicator.

---

views/standard/html/pull.html
views/standard/less/components/pull.less
views/standard/spec/indicators.js

We want to be able to tell how hold a pull is at a glance. This adds the
indicator as well as adds it to the pull element.
Note: We cap the number of dots at 20 but the tooltip still shows the 
correct number of days.
QA:
--
I currently have it set up on https://pulldasher-dev.cominor.com.  Play
around with it! You could open a test pull to ensure it adds the proper
dots.
cc @addison-grant (We both worked on this).

Pulls: Add age indicator

---

bin/dump-schema
controllers/githubHooks.js
lib/db-manager.js
lib/git-manager.js
migrations/0013-add-reviews-table.sql
migrations/schema.sql
models/db_review.js
models/pull.js
models/review.js
models/signature.js

This adds a new reviews table, and the various necessary models, getters, setters, etc. to store and retrieve them from the `metrics` DB.
This also adds the necessary logic to parse signatures (e.g. CR, QA, dev_block) out of the review text, in case people use a GitHub review to sign off on a pull.
QA
---
I tested this pretty extensively locally, but it's probably a good idea to make sure that signatures in Comments and Reviews play nicely together. Editing and deleting comments and reviews (I couldn't figure out how to delete a review), etc. works as expected.
Closes #146
CC @evannoronha

Pull Request Reviews: parse signoffs out of GitHub reviews

---

.travis.yml
controllers/githubHooks.js
lib/db-manager.js
lib/git-manager.js
lib/utils.js

This adds support for GitHub Actions. Normal GitHub status checks should remain unchanged.
We turned on the check_run webhook on the ifixit org. We now listen for that event and create 
a dbStatus which is entered into the DB the same way that commit statuses are.
The manual refresh works by pinging the github api for a given sha. We had to concatenate both
the statuses and the checks. We then pull off the relevant information and send that to the
`commit_statuses` table.
CC @danielbeardsley @BaseInfinity 
Closes https://github.com/iFixit/pulldasher/issues/227

Pulldasher: Add support for GitHub Actions

---

Dockerfile

Previously, the build broke cause node v17 had a backward incompatible change that broke some crypto thing in a dependency.

Dockerfile: commit to node 16 for now

---

frontend/src/navbar.tsx
views/standard/index.html

They aren't formatted exactly the same but they both go to the
right place. Now users can easily click a link to get to either version
of the UI.
The old UI will likely be soon.
Closes #250

Old/New UI: add links between them

---

frontend/src/pull-card/copy-branch.tsx
frontend/src/pull-card/index.tsx
views/standard/less/themes/day_theme.less
views/standard/less/themes/night_theme.less

Add a button to copy the branch name of a given pull to the clipboard.
Old UI has this, but you had to hover, then press Ctrl-C. Most of the time it worked, but there was no feedback.
Hovering the pull shows the button:
Button hovered:
After Successful Copy:

New UI: add copy branch button

---

frontend/src/pulldasher/index.tsx

The old UI excludes these cause it effectively means "contents may
change, don't CR/QA just yet". So we like to keep them off of dev's
radars.

CR/QA Columns: Exclude dev blocked pulls

---

app.js
lib/db-manager.js

Previously, we only loaded pulls that were in our *repo* array from the config.
This meant that after a restart, some pulls may disappear.
We may receive webhooks for repos not in that array,
show the pulls for a while (cause they are in memory), then they
disappear on restart cause they don't get loaded from the DB.
The repo list is now only used on start when we refresh all pulls from
the API (need to know which repos to ask about).
Future Work
====
We may want to support `{orgname}/*` in the repo-list or something.

Backend: load all open pulls from the DB on start

---

frontend/dummy-pulls.json
frontend/src/pull.ts
frontend/src/pulldasher/filtered-pulls-state.ts

The backend won't send us closed pulls in the initial list, but we
hadn't been hiding pulls that *become* closed after the page has been
loaded. This meant that a merged pull would jut sit around in the ready
column, even after it's been closed.
The old UI did this, it was just overlooked.

Frontend: Hide Closed Pulls

---

frontend/dummy-pulls.json
frontend/src/pull-card/flags.tsx
frontend/src/pull.ts
frontend/src/pulldasher/index.tsx

If a pull has no CI statuses and no required statuses, then it should be
in the deploy block column because likely it'll need some manual
intervention for deployment.
Closes #272

Ready Column: exclude pulls with no CI

---

frontend/src/pulldasher/index.tsx

Generally, if a pull is failing CI, we'll need to do more work on it
and QA should spend there energy elsewhere.
So, we'll hide pulls that fail CI from the QA Column.
Closes #282

QA Column: exclude pulls failing CI

---

frontend/src/column.tsx

Instead of showing the total pull count (including filtered pulls),
show just the count of pulls the user sees in the columns.
Closes #269

Column Headers: show visible pull count

---

frontend/src/pulldasher/index.tsx
frontend/src/pulldasher/pulls-context.tsx
frontend/src/pulldasher/sort.ts

As specified in the issue, the order is broken down like this:
* QAing (by current user)
* Everything else
* No external Block
* Not QAing
* Pulls with completed CR
* Sort by oldest first 
* Pulls needing more CR
* Sort by oldest first 
* QAing
* External Block
Closes #280

QA column: Use custom sorting order

---

frontend/src/pull-card/commit-statuses.tsx
frontend/src/pull.ts
frontend/test/named-pulls.ts
frontend/test/pull-card-demo.tsx
frontend/test/pull-data-parts.ts
models/pull.js

If a pull doesn't have a required status, include a grey CI bubble
like the other CI statuses that says "Missing" to make it obvious which
one can't be found.
Think of it as a placeholder for an unmet requirement. Without this,
it's not obvious which of ~13 required statuses isn't present.
Closes #295
CC @davidrans @erinemay

Required Statuses: include "missing" CI bubble

---

frontend/src/filter-menu.tsx

Bug: No divider -> 
Divider in wrong place:
After:
cr_req 1

Filter menu: put the divider in the right place

---

app.js
frontend/src/filter-menu.tsx
frontend/src/leader-list.tsx
frontend/src/pulldasher/index.tsx
frontend/src/pulldasher/pulls-context.tsx
frontend/src/types.ts
frontend/src/utils.ts
lib/db-manager.js
lib/pull-manager.js

The Leader list was not that helpful. It was showing the total
CR signature count across all pulls in pulldasher's memory (not the DB).
This wasn't that useful of a metric because that was an abritrary number
of pulls and 7 CRs on one pull isn't the same as 1 CR on 7 pulls.
Now:
* Only include open pulls and those merged less than 14 days ago.
* Only include signatures made in the last 14 days
* Count only the number of pulls each user has CRed (not the number of
signatures)
* Avatars show username on hover
Future work:
* Change pulldasher to load even closed pulls from the DB so
these numbers stay the same on restart.
* Right now it only loads open pulls on restart
* Maybe: drop list and only show how you compare to mean or median of the
group.
This is closer to your spec @davidrans

CR Leader List: have it show unique CRs in last 14 days

---

frontend/src/pull-card/age.tsx

The age indicator is relative and coarse. Let's add a tooltip that gives
more specifics.
`"opened at 20/12/2012, 03:00:00"`

Pull card: add tooltip of timestamp to age indicator

---

frontend/src/pull-card/index.tsx
frontend/test/pull-data-parts.ts

Apparently, usernames of bots come from github like "{name}[bot]"
and that "[bot]" part needs to be trimmed off when making an avatar url.

Avatars: support bots!

---

frontend/src/pull-card/commit-statuses.tsx
frontend/src/pull-card/index.tsx
frontend/src/pull.ts
frontend/src/theme.tsx
frontend/src/theme/day_theme.less
frontend/src/theme/night_theme.less
frontend/src/utils.ts

See discussion: https://github.com/iFixit/pulldasher/discussions/316
When we have lots of CI statuses (we currently have 15 or so), the current UI works very poorly. This change moves most of it into a popup.
CI Status UI
====
* Use existing UI to represent *groups* of CI builds with the same state, roughly scaling with number in the group
* Keep them in a consistent order with green on top
* Clicking on any group opens the popup
* Hovering shows the list of statuses in that state
Popup:
====
* Consistent ordering (alpha)
* Icon and color both represent build state
**Popup:**
**Hover state**

CI Status: move details into a popup

---

frontend/src/backend/pull-socket.ts
frontend/src/backend/socket.ts
frontend/src/utils.ts

We didn't use to try connecting to the socket when only running the frontend in dev mode, but then we added the connection state display #315 and accidentally started attempting a connection.
Here, we fake the connection status when in dev mode. Previously, when running `frontend:start` we were getting one 404 on the client every 10s or so, now we don't.

Frontend dev: stop socket io connection

---

.gitignore
frontend/src/pull-card/commit-statuses.tsx
frontend/src/theme.tsx

The CI bubbles now scale with the number of status in that state. Previously, the relative scaling was unpredictable.
Closes #321 
**Before:**
**After:**

Commit status: tweak bubble sizes

---

frontend/src/pull-card/avatar.tsx
frontend/src/pull-card/index.tsx
frontend/src/pull-card/signatures.tsx
frontend/src/pull.ts
frontend/src/pulldasher/sort.ts
frontend/src/theme.tsx
frontend/src/theme/day_theme.less
frontend/src/theme/night_theme.less
frontend/src/utils.ts
frontend/test/named-pulls.ts
frontend/test/pull-card-demo.tsx

Closes #298 
Connect #284
Changes the display of signatures, never showing more than one bubble per required CR / QA. Much more details are shown in a popup that's triggered on click.

Signatures: Only show one per requirement

---

frontend/src/navbar.tsx
frontend/src/pulldasher/index.tsx

Add just a dash of mobile support:
* Set a min-width on the columns so the format goes to 2-wide, then 1-wide as it gets smaller
* Hide some header widgets as browser size gets smaller so it's not too crowded
This gets us most of the way there without too much effort.
Connect #325

Mobile support: MVP

---

lib/utils.js

We sometimes skip jobs and want them to not be shown as errors in pulldasher. Let's map `skipped` -> `success` so they don't get stuck in ci_blocked.
Ref: https://ifixit.slack.com/archives/C01DBJK0H7U/p1661213572318169
Closes: https://github.com/iFixit/ifixit/issues/44378

GitHub Actions: Mark skipped jobs as success

---

frontend/src/navbar.tsx

This pull request rearranges the navigation bar to have the notification bell appear before the pull request filtering
https://pulldasher-dev.cominor.com/
qa_req 0

Pulldasher - Organize the NavBar

---

app.js
models/pull.js

* Gracefully deal with null `pull.body`
* Support parsing larger webhook bodies (we've see pretty big ones)
qa_req 0 - I think there's not much to QA here without actually trying it

GitHub webhooks: be tolerant

---

frontend/dummy-pulls.json
frontend/src/closed-pulls.tsx
frontend/src/column.tsx
frontend/src/navbar.tsx
frontend/src/pull-card/index.tsx
frontend/src/pulldasher/filtered-pulls-state.ts
frontend/src/pulldasher/index.tsx
frontend/src/pulldasher/pulls-context.tsx
frontend/src/pulldasher/pulls-state.tsx
frontend/src/pulldasher/sort.ts
frontend/src/theme.tsx
frontend/src/theme/day_theme.less
frontend/src/use-url-state.ts

Adds a new column that shows a sorted array of all the closed pulls from the last two weeks. We already have all this data on the client side. This adds a view on that data to see at a quick glance which pulls were recently merged.
It should:
* Remain sorted with recent merges / closures at the top
* Style closed and merged pulls differently
* Allow being hidden / shown 
* Respect current filters (repo, author, search)
Closes #303

Closed pulls: Add a new column to show recently closed or merged pulls

---

.eslintrc.json
controllers/githubHooks.js
docker-compose.yml
frontend/src/index.tsx
frontend/src/pull-card/commit-statuses.tsx
frontend/src/pull.ts
frontend/src/pulldasher/index.tsx
frontend/src/types.ts
frontend/src/utils.ts
frontend/test/pull-data-parts.ts
lib/authentication.js
lib/db-manager.js
lib/db.js
lib/git-manager.js
lib/utils.js
migrations/0017-commit-statuses--add-date-columns.sql
migrations/schema.sql
models/db_status.js
models/pull.js
models/status.js

Add code to parse started/completed times when dealing with commit statuses and check runs. Include them all through the code and models, making them available on the front end. Also, add a small "duration" indicator next to each CI status.
Note: The main intent for these times is to be able to make a dashboard for CI, the duration UI was just added to demonstrate the data.

Commit Statuses: add started / completed times 

---

frontend/src/pull.ts

Some draft pull requests were making it to the CI Blocked column, these should only be showing in the Dev Blocked column
---
CR: Review https://github.com/iFixit/pulldasher/pull/359/commits/392d4b70557fcb215c5273a9fe2c89b14303462f
QA:
1. Checkout | merge with [`remove-drafts-from-ci-blocked`](https://github.com/iFixit/pulldasher/tree/remove-drafts-from-ci-blocked)
2. `update-pulldasher-dev --run .`
3. Ensure draft pull requests do not show up in the CI Blocked column
---
Closes #337

Draft PRs, don't show in CI Blocked column

---

frontend/src/pull-card/flags.tsx
frontend/src/pull.ts
frontend/src/theme.tsx
frontend/src/theme/day_theme.less
frontend/src/theme/night_theme.less
frontend/test/named-pulls.ts
frontend/test/pull-data-parts.ts

This will automatically add a flag to pull requests that are based off of another branch, which will no longer require pull authors to make a _deploy_block_ signature comment in these instances.
---
1. Added a new function to determine if a pull request is based off another branch
2. Updated the **Deploy Blocked** column filtering
3. Created a new flag const (which is a deployBlock variant)
---
CR: Review to https://github.com/iFixit/pulldasher/pull/360/commits/857744a5f72bd03861d1bf5bb0a0c6c40cca62b1
1. Checkout | merge with [`deploy_block-dependent-prs`](https://github.com/iFixit/pulldasher/tree/deploy_block-dependent-prs)
2. `update-pulldasher-dev --run .`
3. Find/create a pull request that is based off of another branch
4. Ensure that there is a deploy block variant on this pull card …

Deploy block dependent pull requests

---

frontend/src/pull-card/flags.tsx
frontend/src/pull.ts

This href will link to the dependent pull request's base branch (outlined above)

Add href to dependent pull requests

---

frontend/src/pull-card/index.tsx
frontend/src/types.ts

This moves the additions/deletions (shown in the CR column) up toward the pull title

Update lines-changed UI

---

frontend/src/pull.ts
frontend/src/pulldasher/index.tsx

**Before/After**
qa_req 0
Closes #164

Move ready, no-CI pulls

---

lib/git-manager.js
package-lock.json
package.json

The old checks endpoint isn't supported by github's new Fine Grained
Personal Access Tokens; but this equivalent endpoint is.

Commit Checks: Use new api location

---

.github/workflows/build.yml

Update actions checkout and setup-node to `v3`.
Resolves `Node.js 12 actions are deprecated` and `The 'set-output' command is deprecated` warnings.
Check the summary of the `build` CI check and make sure we don't see the following warnings:
- `Node.js 12 actions are deprecated` 
- `The 'set-output' command is deprecated`
Note: `Build: frontend/src/pull-card/index.tsx#L202` warning is unrelated to github actions deprecation warnings. 
connects https://github.com/ifixit/ifixit/issues/47011

GitHub Actions: Resolve warnings

---

frontend/src/navbar.tsx

This pull request will use an empty string if the `title` prop is _falsy_ instead of defaulting to 'undefined'

Fix 'undefined' title

---

models/pull.js

We only end up using the superset allCR and allQA properties, let's not send these across the wire. We didn't even include them in the typescript types, so we can be sure we're not using them.

Pull model: don't send status.CR/QA

---

frontend/dummy-pulls.json
frontend/src/navbar.tsx

This adds an option to hide draft pulls on Pulldasher
I tested it with the dummy pulls, and it looks like it does what I want.

Add "draft" option

---

frontend/src/closed-pulls.tsx

The background of the _Recently Closed Pulls_ section wasn't reaching down to the bottom of the PR list
<details>
<summary> Toggle View </summary> <br>
</details>
---
**CR:** Adds a **height** CSS prop
**QA:** [Overlord Documentation](https://overlord.ifixit.com/Guide/How+to+test+Pulldasher+with+Pulldasher-dev/1124)
This can easily be checked by using browser tools and applying the same property on Pulldasher
---
Closes https://github.com/iFixit/pulldasher/issues/388

Recently Closed Pulls: Fix cut-off

---

frontend/src/navbar.tsx
frontend/src/pull.ts

https://github.com/iFixit/pulldasher/assets/95656772/00812794-b03f-4f95-9a6b-2be23c513277
This adds a button that will allow for filtering pulls that you have authored, wrote a signature on, or deploy/dev blocked
> Additional functionality can easily be added with this 
---
**QA**: [Testing Documentation](https://overlord.ifixit.com/Guide/How+to+test+Pulldasher+with+Pulldasher-dev/1124)
---
Closes #383

Add Personal View

---

frontend/src/pull.ts

This will filter out draft pull requests out from the **Ready** column
Closes https://github.com/iFixit/pulldasher/issues/393

Remove drafts from Ready column

---

frontend/src/navbar.tsx

Drafts are now toggled off by default. Logged in users should see their personal drafts whether or not it is toggled in the nav bar.
Make sure drafts are toggled off by default and check if your personal drafts are still visible
Closes https://github.com/iFixit/pulldasher/issues/397

Default draft pulls toggle to off

---

frontend/src/pulldasher/index.tsx

Pulls that have merge conflicts will no longer show up in the QA column on Pulldasher.
Closes https://github.com/iFixit/pulldasher/issues/396

Pulldasher: Update QA Column Filtering

---

config.example.js
frontend/src/pull.ts
frontend/src/types.ts

We previously could only set `requiredStatuses`. This is great if all ci checks run
on every PR. We want to conditionally run different workflows on different PRs, so
we can't make certain statuses requried.
Instead, let's create a new `ignoredStatuses` that the user can set so that pulldasher
ignores those even if they are failing. 
QA:
--
We should verify that ignored statuses don't affect the ci blocked PRs. You can modify
`/mnt/ebs/etc/pulldasher-dev.config.js` and update pulldasher dev to make sure the
correct pulls are in (or out) of the CI Blocked column on pulldasher-dev.cominor.com.
Connects: https://github.com/iFixit/ifixit/issues/52034
cc @danielbeardsley

Feat: Add ignored statuses

---

bin/migrate
lib/db.js
package-lock.json
package.json

Our DB recently changed which auth mechanisms were allowed. We disabled the native password option (the only one that the mysql npm module supports). Thankfully, the mysql2 module is way more popular now and supports the auth we want and the api is nearly identical.

Replace mysql npm module with mysql2

---

lib/db-manager.js
lib/db.js

Pulldasher was totally broken and would boot until it ran a `REPLACE INTO` query and then crash.
oof, see the second change.
First: The .query().then() was just changed to make use of the new
promise interface instead of promisifying the old callback interface.
It wasn't the problem.
Second: Add support for utf8mb3 to the library (we'll open a pull to add
it upstream). See the code comment.

DB: fix DB connection and query format 

---

config.example.js
frontend/src/filter-menu.tsx
frontend/src/navbar.tsx
frontend/src/pull-card/index.tsx
frontend/src/pulldasher/pulls-context.tsx
frontend/src/pulldasher/pulls-state.tsx
frontend/src/types.ts

It took a long time to get this to behave intuitively. In short, it took
a long to spec it out. How to have it behave when you click one of the
values, how to represent the default state, ...
The feature as implemented:
* FilterMenu has a new prop defaultExcludedValues: string[]
* Without defaultExcludedValues set, it operates exactly as it does now
* When set, the UI has one new "showDefault" state in addition to
existing "showAll"
* In "showDefault", Pulls matching one of the excluded values are hidden
(these excluded values appear de-selected in the UI)
* One click "selects" them and leaves "showDefault" mode
* "Show All" overrides the "default exclusions" and shows everything
Closes #414

FilterMenu: support a "defaultExcludedValues" prop

---

frontend/dummy-pulls.json
frontend/src/pull-card/index.tsx
frontend/src/pull-card/participants.tsx
frontend/src/pull.ts
frontend/src/theme/day_theme.less
frontend/src/theme/night_theme.less
frontend/src/types.ts
frontend/test/named-pulls.ts
frontend/test/pull-card-demo.tsx
frontend/test/pull-data-parts.ts
frontend/webpack.dev.config.js
models/pull.js

This indicates how many unique participants have left a comment or review.
This also allows the "personal view" filter to include pulls you've
commented on.
Note: participants doesn't include the Author because I found myself
having to explicitly exclude the Author every time I was checking for
participants.

Participants: Add a UI component 
