public/js/PullFilter.js, views/standard/spec/index.js, views/standard/spec/utils.js
This allows us to filter pull requests by assignee (actually pull owner for now) and milestone. To use, add parameters to the URL such as `assigned=soriat,sterlinghirsh,suzukichi,copperwall,anthonypileggi&milestone=8%2F29` (the encoded slash will be properly decoded as well). Multiple assignees or milestones may be separated by commas.
See issue #7.
=> Frontend filtering

Gruntfile.js, app.js, controllers/githubHooks.js, lib/authentication.js, lib/db-manager.js, lib/git-manager.js, lib/pull-manager.js, lib/pull-queue.js, lib/socket-auth.js, lib/utils.js, models/comment.js, models/db_label.js, models/pull.js, models/signature.js, views/standard/spec/columns.js, views/standard/spec/debugIndicators.js
This enables jshint on the backend JS and fixes the things it points out. We've been using it on the frontend for a while; this makes sure the backend is also clean.
The changes are mostly tiny--lots of semicolons.
=> JS cleanup

app.js, bin/refresh-all-issues, bin/refresh-issue, bin/refresh-open-issues, config.example.js, controllers/githubHooks.js, lib/db-manager.js, lib/git-manager.js, lib/refresh.js, migrations/0002-issues--add-table.sql, models/db_comment.js, models/db_issue.js, models/db_label.js, models/db_pull.js, models/db_signature.js, models/db_status.js, models/issue.js, package.json, schema.sql
Makes Pulldasher support receiving information about issues and writing
that information to the database. This allows analysis of issues with
SQL.
Connect #7
=> Add issues support to Pulldasher

app.js, lib/db-manager.js
So we don't start out blank.
There's a possibility that we'll load pulls that have been
closed in the meantime, but it's probably better that we
know about them anyway.
Closes #60
=> Startup: Load open pulls from the DB

lib/authentication.js, package.json
Use the correct dependencies and drop the only `let` usage.
Seem commits for more info.
=> Get it working: Correct dependencies

app.js, bin/refresh-issue, bin/refresh-pull, config.example.js, controllers/githubHooks.js, lib/db-manager.js, lib/git-manager.js, lib/pull-manager.js, lib/pull-queue.js, lib/refresh.js, lib/utils.js, migrations/0008-add-repo-primary-key.sql, models/db_comment.js, models/db_issue.js, models/db_label.js, models/issue.js, models/pull.js, public/js/Pull.js, public/js/pullManager.js, schema.sql, views/standard/html/pull.html, views/standard/less/components/pull.less
After the pull to store repository data is merged and working, then this will start reading from it.
Allows pulldasher to read from multiple repositories.
~~Built on top of #81~~ (merged)
Closes iFixit/ifixit#18725
Closes #62
=> Multiple repos load them

config.example.js
Better describe what needs to be created on GitHub when setting up a
Pulldasher instance.
qa_req 0
=> Improve the setup documentation

lib/authentication.js, lib/git-manager.js, lib/refresh.js
When creating a cross-repo pull request, the repo of the pull should be derived from the base branch, not the head branch.
Otherwise we will get 404's from github since we'll be looking for things that don't exist in the wrong repos.
Closes #79
=> Fix cross repo pull requests

views/standard/index.html
This pull adds better column handling to Pulldasher at tablet and below sized viewports.
| Current | Updated |
|---------|---------|
| ![image](https://user-images.githubusercontent.com/1361631/36336707-0ebf7e5e-133f-11e8-8f65-f73d8d20d586.png) ![image](https://user-images.githubusercontent.com/1361631/36336669-b511f666-133e-11e8-80a5-852354b311f2.png)    |  ![image](https://user-images.githubusercontent.com/1361631/36336710-1844e7d4-133f-11e8-9acb-f031f72617d6.png) ![image](https://user-images.githubusercontent.com/1361631/36336664-ae22dbe0-133e-11e8-9366-47308262c276.png)    |
cr_req 1
QA
--
Talk to me, setup on this is a pain.
Closes #129
=> Add logic to fix column stacking in tablet view

package-lock.json, package.json, webpack.config.js
This updates the package.json to use Webpack 4 and updates the
webpack.config.js to be compatible with the new interface.
=> Upgrade to Webpack 4

package-lock.json, package.json
webpack-cli, css-loader, and lint-staged needed to be updated to patch some
vulnerable dependencies.
qa_req 0
=> chore: Add fixes from npm audit to package-lock.json

config.example.js
The old text seems very different from our current configuration.
=> Update description of webhook config

controllers/githubHooks.js
For adding or removing a milestone to a pull, GH sends an "issue event"
cause every pull is *also* an issue.
Previously, we tried to use the body to update the issue in the DB
(which didn't exist). Thus we'd miss those events. Now any time we get
an issue event for a pull, we just refresh that whole pull. We have to
do this cause the body that comes with issue events is incomplete.
qa_req 0
=> Github Pull hooks: refresh on more events

views/standard/html/pull.html
To better contextualize the pull requests
Closes #197
=> Cards: Add repo name

views/standard/less/components/pull.less, views/standard/less/themes/day_theme.less, views/standard/less/themes/night_theme.less, views/standard/spec/indicators.js
We want to keep the colors around because it's a great indication as to
how old the pulls are at a glance. Let's match the colors to the
preexisting colors that we use on the pull cards.
QA:
--
Make sure the colors look good. https://pulldasher-dev.cominor.com/ should be set up.
CC @sterlinghirsh
=> Age: Match preexisting colors

migrations/schema.sql
This is a follow-up to https://github.com/iFixit/ifixit/pull/38592
to keep the pulldasher repo up-to-date
qa_req 0 ~ this will be exercised in testing https://github.com/iFixit/ifixit/pull/38592
Connects #222
=> Update pulldasher schema for `reviews.body`

migrations/0015-commit-statuses--allow-null-log-url.sql, migrations/schema.sql
Some statuses don't have urls, so let's not crash when we get webhooks
about those.
qa_req 0
cr_req 1
=> commit_statuses: allow null log_url

frontend/src/column.tsx, frontend/src/leader-list.tsx, frontend/src/pulldasher/index.tsx, frontend/src/types.ts, frontend/tsconfig.json, frontend/webpack.dev.config.js
=> CR/QA Leaderboard: implement it in React

frontend/src/pull-card/flags.tsx, frontend/src/pull-card/index.tsx, frontend/src/pull.ts, frontend/src/pulldasher/index.tsx, frontend/src/theme.tsx, frontend/src/utils.ts, frontend/test/named-pulls.ts, frontend/test/pull-card-demo.tsx, frontend/test/pull-data-parts.ts
Add flags on the pull cards for:
* `dev_block` signature
* `QAing` label
* `external_block` label
Note: Built on top of #246
=> React Frontend: add Flags and Labels

.github/workflows/build.yml
Pretty much just runs lint + webpack compile
But hey, it's better than nothing.
Closes #229
=> Github Actions: add build step

frontend/src/column.tsx, frontend/src/pulldasher/index.tsx, frontend/src/theme.tsx, frontend/src/use-url-state.ts
Make the individual columns collapsable, and store that state in the url so you can make links to the state and the browser back/forward buttons work.
Closes #253
=> Columns: make Collapsable

frontend/src/navbar.tsx, frontend/src/pull-card/flags.tsx, frontend/src/pulldasher/filtered-pulls-state.ts, frontend/src/pulldasher/pulls-context.tsx, frontend/src/theme.tsx, frontend/test/named-pulls.ts, views/standard/less/themes/day_theme.less
Add a toggle button in the header to show pulls with the `Cyrogenic Storage` label. Hide them by default.
Also, add a flag for these pulls.
Flag when the label is present:
Header button:
Closes #252
=> Cryo Pulls: Hide them and add button to show them

frontend/src/navbar.tsx, frontend/src/pulldasher/index.tsx, views/standard/less/themes/day_theme.less
Also, move the number into a variable.
=> Frontend: increase max width to 1200px

frontend/src/backend/pull-socket.ts, frontend/src/index.tsx, frontend/src/pull-card/index.tsx, frontend/src/pull-card/refresh.tsx, frontend/src/pulldasher/pulls-state.tsx, frontend/src/theme/base.less, frontend/src/types.ts, views/standard/less/themes/day_theme.less
The old UI had a button to refresh pulls from the API. Let's add the same thing to the new UI. Also, add a brief highlight when pulls update.
Closes #258
=> Refresh button: add to pull-card

frontend/index.html, frontend/src/backend/pull-socket.ts, frontend/src/leader-list.tsx, frontend/src/navbar.tsx, frontend/src/pull-card/index.tsx, frontend/src/pull-card/refresh.tsx, frontend/src/theme.tsx, frontend/src/theme/base.less, views/standard/less/themes/day_theme.less, views/standard/less/themes/night_theme.less
Add Darkmode. Most of the previous theme was re-used, it didn't require that much tweaking.
I decided to use the chakra native color mode and piggy-back off its class name. We've set so many customer colors that the built in dark theme pretty much only affects the Search box border.
New button in the header:
=> Darkmode: OMG, lights out

frontend/dummy-pulls.json, frontend/src/pull-card/flags.tsx, frontend/src/pull.ts, frontend/src/pulldasher/index.tsx, frontend/src/types.ts, frontend/test/named-pulls.ts, frontend/test/pull-card-demo.tsx, frontend/test/pull-data-parts.ts, models/pull.js
Some unused code, asserting some assumptions, adding some test data. See commit descriptions for more info.
=> Frontend: A smattering of small fixes

frontend/src/pull-card/commit-statuses.tsx, frontend/src/pull-card/flags.tsx, frontend/src/pull-card/index.tsx
Users almost always want to keep pulldasher open, so let's help them
out.
Closes #281
=> Links: open everything in new tabs

frontend/src/pull-card/signatures.tsx, frontend/src/pull.ts, frontend/src/types.ts, models/pull.js
Have the checkmarks link to the signature comments they came from.
Closes #291
=> CR / QA Sigs: add links to comments

frontend/src/navbar.tsx
Now we show both total pulls *and* the numbered of pulls shown after the
filters.
Closes #270
=> navbar: show total pulls as well

frontend/src/leader-list.tsx, frontend/src/pulldasher/index.tsx
The QA team doesn't feel this is useful, so let's drop it and make the CR list longer.
Closes #276
=> QA leader list: remove it

frontend/src/filter-menu.tsx, frontend/src/navbar.tsx
* Makes repo/author filter more obviously applied
* Adds a "clear search" button
Closes #304
=> Filters  visualize better

frontend/src/navbar.tsx, package-lock.json, package.json
Make `/` a hotkey that focuses the search input. Have it also select all the text in the field
=> Search Input: add hotkey

frontend/src/leader-list.tsx, frontend/src/pull-card/index.tsx, frontend/src/utils.ts
Have avatars in the leader list *and* the pull cards both link to the profile pages.
Closes #299
=> Avatars: link to user profile pages on GH

frontend/src/navbar.tsx
The browser `<input type="search">` has the clear button already, so we can simplify the code.
We can also extract it to a separate component so the navbar component is easier to read.
=> Search: use native browser search input type

frontend/src/navbar.tsx, frontend/src/pulldasher/pulls-context.tsx
Fix unsorted columns, see commits for more info
Bug was introduced when I added `allOpenPulls` and returned the array without sorting
https://github.com/iFixit/pulldasher/pull/300/files#diff-4894e3876cc8c65384780c691d91fbbed9c96f3e8251e48fbf96429e24f173d5R51
Thanks @mlahargou for finding this!
Closes #312
=> [fix] My pulls were no longer on top

frontend/src/notifications.tsx
If the feature isn't available, don't try to use it.
Noticing "undefined variable 'Notification'" errors on iPhones.
=> Notifications: detect missing feature

frontend/src/navbar.tsx, frontend/src/theme/base.less, package.json
> CR: Review to https://github.com/iFixit/pulldasher/pull/334/commits/5c04bb9da71fbfa6362f70d933506222f98b144a
> QA: https://pulldasher-dev.cominor.com/
>
>I updated Pulldasher-Dev, so you should just be able to click the link above.
>If the changes aren't present, here is a [reference for testing](https://overlord.ifixit.com/Guide/How+to+test+Pulldasher+with+Pulldasher-dev/1124)
cr_req 2
Closes #333
=> Toggle view blocked pull requests

frontend/src/notifications.tsx, frontend/webpack.dev.config.js
This uses the correct URL for the bell sound which is supposed to be available for Pulldasher.
1. Run the UI with `npm run start`.
2. Listen for the bell sound when the page loads.
=> Notifications: Make sound work

frontend/src/column.tsx, frontend/src/pull-card/index.tsx, frontend/src/pulldasher/index.tsx, frontend/src/theme/day_theme.less, frontend/src/theme/night_theme.less, frontend/src/types.ts, frontend/test/named-pulls.ts, frontend/test/pull-card-demo.tsx, frontend/test/pull-data-parts.ts, models/pull.js
---
1. Included additions/deletions fields in PullData
2. Added a new pull card
3. Added a column property
4. Set a conditional render
Review to https://github.com/iFixit/pulldasher/pull/365/commits/c4cedb535a9d83a3fd919608335f6ef40ea87cff
---
Closes #225
=> Add lines changed for CR column

frontend/src/pull-card/index.tsx, frontend/src/types.ts
The lines-changed component wasn't being shown correctly when a pull request had no additions/deletions. This was a bug in the logic for rendering the component, which this pull request resolves.
---
1. Updated the logic for the _linesChanged_ const
=> Fix lines-changed bug

lib/git-manager.js
Before this, an API request would face and github's client doesn't tell us *which* one.
I also took the time to add repo to all of the debug messages.
Closes #371
=> Github: log errors on every promise-returning function

frontend/src/pulldasher/index.tsx
=> Update "Ready" column logic

config.example.js, controllers/main.js, frontend/index.html, frontend/src/navbar.tsx, frontend/src/page-context.ts
=> Set title for Pulldasher-Dev

frontend/src/navbar.tsx
_Before_
**After**
---
Closes #335
=> Search: Add repository pattern
